site_name: Jieke Choo Home Page
theme: 
  name: material
repo_url: https://github.com/jiekechoo
nav:
  - Home: 
    - index.md
  - About: 
    - about.md
plugins:
  - blog:
      blog_toc: true
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      archive: false
      categories: true
      categories_toc: true
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_url_format: '{date}/{file}'
      archive_date_format: yyyy
  - mkdocs-video:
      video_autoplay: False
  # - with-pdf:
  #     cover_subtitle: 上海亿琪软件有限公司
  #     cover_logo: 'assets/illustration.png'
  # - minify:
  #   minify_html: true
  - search:
      lang:
        #       - en
        - zh
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - meta-descriptions
  - swagger-ui-tag
extra: 
  generator: false
  analytics:
    provider: google
    property: G-X0TK2L1BYW
    feedback:
      title: 此文章有帮助吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 此文章有帮助
          data: 1
          note: >-
            感谢你的反馈！
        - icon: material/emoticon-sad-outline
          name: 此文章需要改进
          data: 0
          note: >-
            感谢你的反馈! 帮助我们改进此文章，请联系我们。