name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-swagger-ui mkdocs-swagger-ui-tag mkdocs-video \
          mkdocs-redirects mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin \
          mkdocs-git-revision-date-localized-plugin mkdocs-awesome-pages-plugin mkdocs-glightbox mkdocs-blogging-plugin mkdocs-extra-sass-plugin \
          paginate 
      - name: Build docs
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # mkdocs 默认生成到 ./site 目录